myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
	path('apply/', views.coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('s/', include('short.urls', namespace='short')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
	path('create/', views.order_create, name='order_create'),
	path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
	path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

myshop/shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'

urlpatterns = [
	path('', views.product_list, name='product_list'),
	path('product/search/', views.search, name='search'),
	path('about/', views.about, name='about'),
	path('help/', views.help, name='help'),
	path('term/', views.term, name='term'),
	path('contact/', views.contact, name='contact'),
	path('tag/<slug:tag_slug>/', views.product_list, name='product_list_by_tag'),
	path('<slug:person_slug>/', views.product_list, name='product_list_by_people'),
	path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from django.contrib.auth.decorators import login_required


@login_required
@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
	coupon_apply_form = CouponApplyForm()
	return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
	Your shopping cart
{% endblock %}

{% block content %}
<div class="cart_area section_padding_100 clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="cart-table clearfix">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Quantity</th>
                                        <th>Remove</th>
                                        <th>Unit Price</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                            {% for item in cart %}
							{% with product=item.product %}
                                    <tr>
                                        <td class="cart_product_img d-flex align-items-center">
                                            <a href="#"><img src="{{ product.image.url }}" alt="Product"></a>
                                            <h6>{{ product.name }}</h6>
                                        </td>

                                       	<td>
											<form action="{% url 'cart:cart_add' product.id %}" method="post">
											{{ item.update_quantity_form.quantity }}
											{{ item.update_quantity_form.update }}
											<input type="submit" value="Update">
											{% csrf_token %}
											</form>
										</td>
                                        <td>
											<a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
										</td>
										<td class="num">{{ item.price }} MMK</td>
										<td class="num">{{ item.total_price }} MMK</td>
                                    </tr>
                                {% endwith %}
                                {% endfor %}

                               	{% if cart.coupon %}
									<tr class="subtotal">
									    <td>Subtotal</td>
									    <td colspan="3"></td>
									    <td class="num">
									    	{{ cart.get_total_price|floatformat:"2" }} MMK
										</td>
									</tr>
									<tr>
									    <td>coupon ( {{ coupon.discount }} % off)</td>
									    <td colspan="3"></td>
									    <td class="num neg">
									    	- {{ cart.get_discount|floatformat:"2" }} MMK
									    </td>
									</tr>
                               	{% endif %}
								    <tr class="total">
								        <td>Total</td>
								        <td colspan="3"></td>
								        <td>
								{{ cart.get_total_price_after_discount|floatformat:"2" }} MMK
								        </td>
								    </tr>

                                </tbody>
                            </table>
                        </div>

                        <div class="cart-footer d-flex mt-30">
                            <div class="back-to-shop w-50">
                                <a href="{% url 'shop:product_list' %}">Continue shooping</a>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="row" style="margin-top: 100px;">
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="coupon-code-area mt-70">
                            <div class="cart-page-heading">
                                <h5>Cupon code</h5>
                                <p>Enter your cupone code</p>
                            </div>
                            <form action="{% url 'coupons:apply' %}" method="post">
                            	    {{ coupon_apply_form }}
								    <button type="submit" style="margin-top:32px">Apply</button>
								    {% csrf_token %}
                            </form>

                        </div>
                    </div>
                    <!-- <div class="col-12 col-md-6 col-lg-4">
                        <div class="shipping-method-area mt-70">
                            <div class="cart-page-heading">
                                <h5>Payment</h5>
                                <p>Choose your payment</p>
                            </div>

                            <div class="custom-control custom-radio mb-30">
                                <input type="radio" id="customRadio1" name="customRadio" class="custom-control-input">
                                <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio1"><span>Cash On Delivery</span></label>
                            </div>

                            <div class="custom-control custom-radio mb-30">
                                <input type="radio" id="customRadio2" name="customRadio" class="custom-control-input">
                                <label class="custom-control-label d-flex align-items-center justify-content-between" for="customRadio2"><span>Prepaid</span></label>
                            </div>
                        </div>
                    </div> -->
                    <div class="col-12 col-lg-8">
                        <div class="cart-total-area mt-70">
                            <div class="cart-page-heading">
                                <h5>Cart total</h5>
                                <p>Invoice</p>
                            </div>

                            <ul class="cart-total-chart">
                                <li><span><strong>Total</strong></span> <span><strong>
                                {{ cart.get_total_price_after_discount|floatformat:"2" }} MMK
                                </strong></span></li>
                            </ul>
                            <a href="{% url 'orders:order_create' %}" class="btn karl-checkout-btn">Checkout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}