myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('', views.cart_detail, name='cart_detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('s/', include('short.urls', namespace='short')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from .import views

app_name = 'shop'

urlpatterns = [
	path('', views.product_list, name='product_list'),
	path('product/search/', views.search, name='search'),
	path('about/', views.about, name='about'),
	path('help/', views.help, name='help'),
	path('term/', views.term, name='term'),
	path('contact/', views.contact, name='contact'),
	path('tag/<slug:tag_slug>/', views.product_list, name='product_list_by_tag'),
	path('<slug:person_slug>/', views.product_list, name='product_list_by_people'),
	path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
	path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField

class About(models.Model):
    title = models.CharField(max_length=255)
    body = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title

class Contact(models.Model):
	sno = models.AutoField(primary_key=True)
	name = models.CharField(max_length=255)
	email = models.EmailField()
	content = models.TextField()

	def __str__(self):
		return 'Message from ' + self.name + ' using ' + self.email

class Help(models.Model):
    title = models.CharField(max_length=255)
    body = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title

class Term(models.Model):
    title = models.CharField(max_length=255)
    body = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title

class Person(models.Model):
	name = models.CharField(max_length=255, db_index=True)
	slug = models.SlugField(max_length=255, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'person'
		verbose_name_plural = 'people'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_people', args=[self.slug])

class Category(models.Model):
	name = models.CharField(max_length=255, db_index=True)
	slug = models.SlugField(max_length=255, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])

class Brand(models.Model):
	name = models.CharField(max_length=255, db_index=True)
	slug = models.SlugField(max_length=255, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'brand'
		verbose_name_plural = 'brands'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_brand', args=[self.slug])

class Color(models.Model):
	name = models.CharField(max_length=255, db_index=True)
	slug = models.SlugField(max_length=255, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'color'
		verbose_name_plural = 'colors'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_color', args=[self.slug])

class Size(models.Model):
	name = models.CharField(max_length=255, db_index=True)
	slug = models.SlugField(max_length=255, unique=True)

	class Meta:
		ordering = ('name',)
		verbose_name = 'size'
		verbose_name_plural = 'sizes'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_list_by_size', args=[self.slug])


class Product(models.Model):
	person = models.ForeignKey(Person, related_name='products', on_delete=models.CASCADE)
	category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
	brand = models.ForeignKey(Brand, related_name='products', on_delete=models.CASCADE)
	brand_type = models.CharField(max_length=255, default='Local Brand')
	name = models.CharField(max_length=200, db_index=True)
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
	image_2 = models.ImageField(upload_to='products/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
	image_3 = models.ImageField(upload_to='products/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
	image_4 = models.ImageField(upload_to='products/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
	color = models.ForeignKey(Color, related_name='products', on_delete=models.CASCADE)
	size = models.ForeignKey(Size, related_name='products', on_delete=models.CASCADE)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	tags = TaggableManager()
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ('name',)
		index_together = (('id', 'slug'),)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('shop:product_detail', args=[self.id, self.slug])

class MainBanner(models.Model):
    image1 = models.ImageField(upload_to='covers/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
    text1 = models.CharField(max_length=255)
    body1 = models.CharField(max_length=255)

    def __str__(self):
        return self.text1

class BrandBanner(models.Model):
    image2 = models.ImageField(upload_to='covers/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
    text2 = models.CharField(max_length=255)
    body2 = models.CharField(max_length=255)

    def __str__(self):
        return self.text2

class BrandBanner2(models.Model):
    banner2image = models.ImageField(upload_to='covers/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
    banner2text2 = models.CharField(max_length=255)
    banner2body2 = models.CharField(max_length=255)

    def __str__(self):
        return self.banner2text2

class EventBanner(models.Model):
    image3 = models.ImageField(upload_to='covers/%Y/%m/%d', default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg')
    text3 = models.CharField(max_length=255)
    body3 = models.CharField(max_length=255)

    def __str__(self):
        return self.text3

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Person, Product, Category, Brand, Color, Size, MainBanner, BrandBanner, EventBanner, BrandBanner2, About, Help, Term, Contact
from cart.forms import CartAddProductForm
from taggit.models import Tag
from django.db.models import Count
from django.db.models import Q

def contact(request):
	if request.method == 'POST':
	    name = request.POST['name']
	    email = request.POST['email']
	    content = request.POST['content']
	    print(name, email, content)
	    contact = Contact(name=name, email=email, content=content)
	    contact.save()
	return render(request, 'shop/contact.html')


def about(request):
    about = About.objects.all()
    return render(request, "shop/about.html", {'about':about})

def help(request):
    help = Help.objects.all()
    return render(request, "shop/help.html", {'help':help})

def term(request):
    term = Term.objects.all()
    return render(request, "shop/term.html", {'term':term})

def search(request):
	query = request.GET.get('q')
	products = Product.objects.filter(Q(name__icontains=query) | Q(brand_type__icontains=query)).order_by('-created')
	people = Person.objects.filter(Q(name__icontains=query))
	category = Category.objects.filter(Q(name__icontains=query))
	brand = Brand.objects.filter(Q(name__icontains=query))
	color = Color.objects.filter(Q(name__icontains=query))
	size = Size.objects.filter(Q(name__icontains=query))
	context = {
		'products':products,
		'people':people,
		'category':category,
		'brand':brand,
		'color':color,
		'size':size,
	}
	return render(request, "shop/product/list.html", context)

def product_list(request, person_slug=None, tag_slug=None, category_slug=None):
	person = None
	people = Person.objects.all()
	products = Product.objects.order_by('-created')
	category = None
	categories = Category.objects.all()
	covers1 = MainBanner.objects.all()
	covers2 = BrandBanner.objects.all()
	covers3 = EventBanner.objects.all()
	covers4 = BrandBanner2.objects.all()
	tag = None
	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		products = products.filter(tags__in=[tag])
	if person_slug:
		person = get_object_or_404(Person, slug=person_slug)
		products = products.filter(person=person)
	if category_slug:
	    category = get_object_or_404(Category, slug=category_slug)
	    categories = categories.filter(category=category)
	return render(request, 'shop/product/list.html', {'person': person, 'people': people, 'products': products, 'tag': tag, 'category':category, 'categories':categories, 'covers1':covers1, 'covers2':covers2, 'covers3':covers3, 'covers4':covers4})

def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	product_tags_ids = product.tags.values_list('id', flat=True)
	similar_products = Product.objects.filter(tags__in=product_tags_ids).exclude(id=product.id)
	similar_products = similar_products.annotate(same_tags=Count('tags')).order_by('-same_tags')[:5]
	cart_product_form = CartAddProductForm()
	return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form, 'similar_products': similar_products})

myshop/shop/templates/shop/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Yate - Your trusted Shopping Website</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'shop/img/core-img/favicon.png' %}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'shop/css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'shop/style.css' %}">

    <!-- Responsive CSS -->
    <link href="{% static 'shop/css/responsive.css' %}" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <!-- ****** Header Area Start ****** -->
        <header class="header_area">
            <!-- Top Header Area Start -->
            <div class="top_header_area">
                <div class="container h-100">
                    <div class="row h-100">
                        <div class="col-12 d-md-flex justify-content-between align-items-center mt-2">
                            <!-- <div class="top_single_area d-flex align-items-center"> -->
                                <!-- Logo Area -->
                                <div class="top_logo">
                                    <a href="{% url 'shop:product_list' %}"><img src="{% static 'shop/img/core-img/logo.png' %}" alt="Logo"></a>
                                </div>

                            <!-- </div> -->
                        </div>

                    </div>
                </div>
            </div>

            <!-- Top Header Area End -->

        </header>
        <!-- ****** Header Area End ****** -->

        <!-- ****** History Area Start ****** -->
        <div class="section_padding_100 clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="help-card">
                        {% for x in about %}
                            <h4 class="help-question">{{ x.title }}</h4>
                            <div class="help-answer">
                                {{ x.body|safe }}
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ****** History Area End ****** -->

        <!-- ****** Footer Area Start ****** -->
        <footer class="footer_area">
            <div class="container">
                <div class="row">
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="single_footer_area">
                            <div class="footer-logo">
                                <img src="{% static 'shop/img/core-img/logo.png' %}" alt="">
                            </div>
                            <div class="copywrite_text d-flex align-items-center">
                                <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved </p>
                            </div>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
                        <div class="single_footer_area">
                            <ul class="footer_widget_menu">
                                <li><a href="{% url 'shop:about' %}">About</a></li>
                                <li><a href="{% url 'shop:term' %}">Terms & Conditions</a></li>
                                <li><a href="{% url 'shop:help' %}">Faq</a></li>
                                <li><a href="{% url 'shop:contact' %}">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
                        <div class="single_footer_area">
                            <ul class="footer_widget_menu">
                                <li><a href="{% url 'profile' %}">My Account</a></li>
                                <li><a href="{% url 'shop:term' %}">Our Policies</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-lg-5">
                        <div class="single_footer_area">
                            <div class="footer_heading mb-30">
                                <h6>Follow for more information</h6>
                            </div>
                            <div class="subscription_form">
                                <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FYate-106042591301293%2F&tabs=timeline&width=340&height=200&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="200" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="line"></div>

                <!-- Footer Bottom Area Start -->
                <div class="footer_bottom_area">
                    <div class="row">
                        <div class="col-12">
                            <div class="footer_social_area text-center">
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- ****** Footer Area End ****** -->
    </div>
    <!-- /.wrapper end -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="{% static 'shop/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'shop/js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'shop/js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'shop/js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'shop/js/active.js' %}"></script>

    <script>
        $("#account-details-form").change(function(){
            $(".account-update-btn").removeAttr("disabled")
        })
    </script>

</body>

</html>

myshop/shop/templates/shop/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Yate - Your trusted Shopping Website</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'shop/img/core-img/favicon.png' %}">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'shop/css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'shop/style.css' %}">

    <!-- Responsive CSS -->
    <link href="{% static 'shop/css/responsive.css' %}" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <!-- ****** Header Area Start ****** -->
        <header class="header_area">
            <!-- Top Header Area Start -->
            <div class="top_header_area">
                <div class="container h-100">
                    <div class="row h-100">
                        <div class="col-12 d-md-flex justify-content-between align-items-center mt-2">
                            <!-- <div class="top_single_area d-flex align-items-center"> -->
                                <!-- Logo Area -->
                                <div class="top_logo">
                                    <a href="{% url 'shop:product_list' %}"><img src="{% static 'shop/img/core-img/logo.png' %}" alt="Logo"></a>
                                </div>

                            <!-- </div> -->
                        </div>

                    </div>
                </div>
            </div>

            <!-- Top Header Area End -->

        </header>
        <!-- ****** Header Area End ****** -->



        <!-- ****** History Area Start ****** -->
        <div class="order_history_area section_padding_100 clearfix">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="contact_area mt-50 clearfix">
                            <div class="contact-page-heading">
                                <h5>Contact Information</h5>
                            </div>

                            <div class="col-12 mb-10 contact-information">
                                <p>ADDRESS : No123, Street Name, Yangon</p>
                                <p>EMAIL : marketing@yate.com</p>
                                <p>PHONE : +123 456 789</p>
                                <div id="map"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="contact_area mt-50 clearfix">
                            <div class="contact-page-heading">
                                <h5>Contact Form</h5>
                            </div>
<form method="POST">
    {% csrf_token %}
	<div class="form-group">
		<input type="text" class="form-control" name='name' id='name' placeholder="Name">
	</div>
	<div class="form-group">
		<input type="email" name='email' id='email' class="form-control" placeholder="Email">
	</div>
	<div class="form-group">
		<textarea name='content' id='content' class="form-control" cols="30" rows="10" placeholder="Message" ></textarea>
	</div>
	<div class="form-group">
		<input type="submit" class="btn contact-btn" value="Send">
	</div>
</form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- ****** History Area End ****** -->

        <!-- ****** Footer Area Start ****** -->
        <footer class="footer_area">
            <div class="container">
                <div class="row">
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="single_footer_area">
                            <div class="footer-logo">
                                <img src="img/core-img/logo.png" alt="">
                            </div>
                            <div class="copywrite_text d-flex align-items-center">
                                <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved </p>
                            </div>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                   <div class="col-12 col-sm-6 col-md-3 col-lg-2">
                        <div class="single_footer_area">
                            <ul class="footer_widget_menu">
                                <li><a href="{% url 'shop:about' %}">About</a></li>
                                <li><a href="{% url 'shop:term' %}">Terms & Conditions</a></li>
                                <li><a href="{% url 'shop:help' %}">Faq</a></li>
                                <li><a href="{% url 'shop:contact' %}">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-sm-6 col-md-3 col-lg-2">
                        <div class="single_footer_area">
                            <ul class="footer_widget_menu">
                                <li><a href="{% url 'profile' %}">My Account</a></li>
                                <li><a href="{% url 'shop:term' %}">Our Policies</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Single Footer Area Start -->
                    <div class="col-12 col-lg-5">
                        <div class="single_footer_area">
                            <div class="footer_heading mb-30">
                                <h6>Follow for more information</h6>
                            </div>
                            <div class="subscription_form">
                                <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FYate-106042591301293%2F&tabs=timeline&width=340&height=200&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="340" height="200" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="line"></div>

                <!-- Footer Bottom Area Start -->
                <div class="footer_bottom_area">
                    <div class="row">
                        <div class="col-12">
                            <div class="footer_social_area text-center">
                                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- ****** Footer Area End ****** -->
    </div>
    <!-- /.wrapper end -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="{% static 'shop/css/responsive.css' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'shop/js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'shop/js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'shop/js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'shop/js/active.js' %}"></script>
    <!-- Map API -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBp3Ugg_jupQ3mkaY4xkAzH0GgRCW6I1RM&callback=initMap&libraries=&v=weekly"
      defer
    ></script>
    <script>
        // Initialize and add the map
      function initMap() {
        // The location of Uluru
        const location = { lat: 16.774384, lng: 96.158802 };
        // The map, centered at Uluru
        const map = new google.maps.Map(document.getElementById("map"), {
          zoom: 16,
          center: location,
        });
        // The marker, positioned at Uluru
        const marker = new google.maps.Marker({
          position: uluru,
          map: map,
        });
      }
    </script>

</body>

</html>